update scripts for jsc-zen2 to support testing in a container
boegel/boegelbot pull request #21
Opened 2022-10-26 18:36 UTC by boegel

@SebastianAchilles This is a quick port of the equivalent scripts for `generoso`, but it should work.

Only problem is that Singularity or Apptainer are not available yet on `jsc-zen2`, can that be fixed?

2022-10-26 18:40 UTC, SebastianAchilles requested changes

2022-10-26 18:40 UTC, SebastianAchilles commented on eb_from_pr_upload_jsc-zen2.sh
> +export CPU_ARCH=haswell
```suggestion
export CPU_ARCH=zen2
```

2022-10-26 18:40 UTC, SebastianAchilles commented
Yes, I will look into making Singularity available on `jsc-zen2`.

2022-10-26 18:43 UTC, boegel commented on eb_from_pr_upload_jsc-zen2.sh
> +export CPU_ARCH=haswell
Ah, silly copy-pasting mistake 🤦

2022-10-26 18:43 UTC, boegel commented
> Yes, I will look into making Singularity available on `jsc-zen2`.

Better go straight for Apptainer?

2024-05-15 16:32 UTC, SebastianAchilles commented
This PR can be closed, as `jsc-zen2` is no longer in production and the functionality has been added to `jsc-zen3`.

2024-06-05 19:57 UTC, closed without merging