Use correct repo name for easyblocks
boegel/boegelbot pull request #27
Opened 2023-09-08 13:58 UTC by ocaisa

2023-09-08 15:16 UTC, SebastianAchilles approved these changes
lgtm

2023-09-08 15:36 UTC, SebastianAchilles requested changes

2023-09-08 15:36 UTC, SebastianAchilles commented on eb_from_pr_upload_generoso.sh
> +if [ "EB_REPO" == "easybuild-easyblocks" ]; then
```suggestion
if [ $EB_REPO == "easybuild-easyblocks" ]; then
```

2023-09-08 15:36 UTC, SebastianAchilles commented on eb_from_pr_upload_jsc-zen2.sh
> +if [ "EB_REPO" == "easybuild-easyblocks" ]; then
```suggestion
if [ $EB_REPO == "easybuild-easyblocks" ]; then
```

2023-09-08 16:27 UTC, ocaisa commented
Thanks for the fixes @SebastianAchilles

2023-09-09 08:10 UTC, boegel approved these changes

2023-09-09 08:10 UTC, merged

2023-09-09 08:12 UTC, boegel commented
deployed on both `jsc-zen2` and `generoso`